# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Definição da box
  config.vm.box = "ubuntu/jammy64"

  # Configurando a rede pública com IP fixo
  config.vm.network "public_network", bridge: "eth0"

  # Definindo o hostname da VM
  config.vm.hostname = "ubuntu-worker-1"

  # Configurando memória e CPU para a VM
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Provisionamento: Comandos para instalar pacotes e configurar SSH
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update -y
    sudo apt install -y nano net-tools openssh-server
    sudo systemctl enable ssh
    sudo ufw allow ssh
    sudo systemctl start ssh
    curl -sSL https://get.docker.com/ | sh -y
    sudo usermod -aG docker $(whoami)
    sudo service docker start
  SHELL

  # Porta de redirecionamento para acessar o Apache (opcional, caso prefira acessar via IP)
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Sincronizando pastas locais para a VM (opcional)
  # config.vm.synced_folder "./wordpress", "/srv/www/wordpress"
end


