apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diskpressure-operator
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "delete"]
